# .github/workflows/sync-upstream.yml
name: Sync from upstream

on:
  # every 6 hours; adjust as you like
  schedule:
    - cron: '0 0 * * 1'
  # allow manual runs
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        # fetch full history so we can merge

      - name: Add upstream remote & fetch
        run: |
          git remote add upstream https://github.com/Vendicated/Vencord
          git fetch upstream

      - name: Merge upstream/main into main
        run: |
          git checkout main
          git merge upstream/main --no-ff --no-edit

      - name: Remove unwanted upstream workflows
        run: |
          rm -f .github/workflows/codeberg-mirror.yml
          rm -f .github/workflows/reportBrokenPlugins.yml
          # (keep build.yml, test.yml, publish.yml)

      - name: Commit deletions if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/workflows
          git diff-index --quiet HEAD || git commit -m "chore: prune unwanted upstream workflows"

      - name: Push cleaned main back to your fork
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
